services:
  appsmith:
    image: appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      # Appsmith内部データベースはSQLiteを使用（PostgreSQL v0012マイグレーションバグ回避）
      # - APPSMITH_DB_URL=postgresql://${APPSMITH_DB_USERNAME}:${APPSMITH_DB_PASSWORD}@${APPSMITH_DB_HOST}:${APPSMITH_DB_PORT}/${APPSMITH_DB_NAME}
      - APPSMITH_ENCRYPTION_PASSWORD=${APPSMITH_ENCRYPTION_PASSWORD}
      - APPSMITH_ENCRYPTION_SALT=${APPSMITH_ENCRYPTION_SALT}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: anstack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anstack_pass
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d anstack"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
