services:
  appsmith:
    image: appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8080:80"
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
