version: "3.8"
services:
  appsmith:
    image: appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8080:80"
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      # 必要に応じて追加設定

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: anstackdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anstack_pass
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
